## Objective

To load all raw Olist datasets and validate their structural integrity by checking shapes, data types, missing values, duplicates, and primary key uniqueness.  
No joins, cleaning logic, or visualizations are performed in this notebook.

In [10]:
import numpy as np
import pandas as pd

In [11]:
customers = pd.read_csv('olist_customers_dataset.csv')
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [12]:
orders = pd.read_csv("olist_orders_dataset.csv")
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [13]:
items = pd.read_csv("olist_order_items_dataset.csv")
items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [14]:
payments = pd.read_csv("olist_order_payments_dataset.csv")
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [15]:
reviews = pd.read_csv("olist_order_reviews_dataset.csv")
reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [16]:
geolocations = pd.read_csv("olist_geolocation_dataset.csv")
geolocations.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [17]:
sellers = pd.read_csv("olist_sellers_dataset.csv")
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [18]:
products = pd.read_csv("olist_products_dataset.csv")
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [19]:
name_translations = pd.read_csv("product_category_name_translation.csv")
name_translations.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [20]:
# Check shapes
print(f"Customers dataset shape {customers.shape}")                 # 1
print(f"Orders dataset shape {orders.shape}")                       # 2
print(f"Items dataset shape {items.shape}")                         # 3
print(f"Payments dataset shape {payments.shape}")                   # 4
print(f"Reviews dataset shape {reviews.shape}")                     # 5
print(f"Geolocations dataset shape {geolocations.shape}")           # 6
print(f"Sellers dataset shape {sellers.shape}")                     # 7
print(f"Products dataset shape {products.shape}")                   # 8
print(f"Name translations dataset shape {name_translations.shape}") # 9

Customers dataset shape (99441, 5)
Orders dataset shape (99441, 8)
Items dataset shape (112650, 7)
Payments dataset shape (103886, 5)
Reviews dataset shape (99224, 7)
Geolocations dataset shape (1000163, 5)
Sellers dataset shape (3095, 4)
Products dataset shape (32951, 9)
Name translations dataset shape (71, 2)

In [25]:
# Check dtypes
dataframes = {
    "Customers": customers,
    "Orders": orders,
    "Items": items,
    "Payments": payments,
    "Reviews": reviews,
    "Geolocations": geolocations,
    "Sellers": sellers,
    "Products": products,
    "Name Translations": name_translations
}

for name, df in dataframes.items():
    print(f"{name} dtypes :")
    print(df.dtypes)
    print("\n")

Customers dtypes :
customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object


Orders dtypes :
order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object


Items dtypes :
order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object


Payments dtypes :
order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object


Reviews dtypes :
review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object


Geolocations dtypes :
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object


Sellers dtypes :
seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object


Products dtypes :
product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object


Name Translations dtypes :
product_category_name            object
product_category_name_english    object
dtype: object

In [29]:
# Missing values summary
for name, df in dataframes.items():
    missing = df.isnull().sum()
    if missing.sum() > 0:
        print(f"Missing Values in {name} :")
        print(missing[missing > 0])
        print("\n")
    else:
        print(f"{name}: No missing values found !!\n")

Customers: No missing values found !!

Missing Values in Orders :
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
dtype: int64


Items: No missing values found !!

Payments: No missing values found !!

Missing Values in Reviews :
review_comment_title      87656
review_comment_message    58247
dtype: int64


Geolocations: No missing values found !!

Sellers: No missing values found !!

Missing Values in Products :
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64


Name Translations: No missing values found !!

In [33]:
# Duplicate keys check
key_audit = {
    "Customers": [customers, "customer_id"],
    "Orders": [orders, "order_id"],
    "Items": [items, "order_item_id"],
    "Payments": [payments, "order_id"],
    "Reviews": [reviews, "review_id"],
    "Sellers": [sellers, "seller_id"],
    "Products": [products, "product_id"]
}
for name, (df, key) in key_audit.items():
    duplicates = df.duplicated(subset=[key]).sum()
    if duplicates > 0:
        print(f"{name}: Found {duplicates} duplicate keys in '{key}'")
        # print(df[df.duplicated(subset=[key], keep=False)])
    else:
        print(f"{name}: '{key}' is unique.")

Customers: 'customer_id' is unique.
Orders: 'order_id' is unique.
Items: Found 112629 duplicate keys in 'order_item_id'
Payments: Found 4446 duplicate keys in 'order_id'
Reviews: Found 814 duplicate keys in 'review_id'
Sellers: 'seller_id' is unique.
Products: 'product_id' is unique.

In [38]:
# Validate primary keys
primary_keys = {
    "Customers": (customers, "customer_id"),
    "Orders": (orders, "order_id"),
    "Sellers": (sellers, "seller_id"),
    "Products": (products, "product_id"),
    "Reviews": (reviews, "review_id"),
    "Geolocations": (geolocations, "geolocation_zip_code_prefix")
}
print(f"{'Table':<20} | {'Total Rows':<10} | {'Unique IDs':<10} | {'Duplicates':<10} | {'Nulls':<5}")
print("-" * 65)
for name, (df, pk) in primary_keys.items():
    total = len(df)
    unique = df[pk].nunique()
    dupes = df[pk].duplicated().sum()
    nulls = df[pk].isnull().sum()

    status = "" if dupes == 0 and nulls == 0 else ""

    print(f"{name:<20} | {total:<10} | {unique:<10} | {dupes:<10} | {nulls:<5} {status}")

Table                | Total Rows | Unique IDs | Duplicates | Nulls
-----------------------------------------------------------------
Customers            | 99441      | 99441      | 0          | 0
Orders               | 99441      | 99441      | 0          | 0
Sellers              | 3095       | 3095       | 0          | 0
Products             | 32951      | 32951      | 0          | 0
Reviews              | 99224      | 98410      | 814        | 0
Geolocations         | 1000163    | 19015      | 981148     | 0

## Key Takeaways

1. **Data Loading**: All nine Olist datasets were successfully loaded.

2. **Data Types**: Some date columns in `orders` and `reviews` are stored as `object` and need conversion to `datetime`. Numeric columns in `products` are fine.

3. **Missing Values**: Present in `orders`, `reviews`, and `products` with varying counts.

4. **Primary Key Checks**:
   - **Unique**: `customer_id`, `order_id`, `seller_id`, `product_id`.
   - **Not unique**: `review_id` (duplicates present), `order_item_id` & `order_id` in `Payments` (expected composite keys), `geolocation_zip_code_prefix` (expected).